name: pandora
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - libexpat=2.7.0=h240833e_0
  - libffi=3.4.6=h281671d_1
  - liblzma=5.8.1=hd471939_0
  - liblzma-devel=5.8.1=hd471939_0
  - libsqlite=3.49.1=hdb6dae5_2
  - libzlib=1.3.1=hd23fc13_2
  - ncurses=6.5=h0622a9a_3
  - openssl=3.5.0=hc426f3f_1
  - pip=24.3.1=pyh8b19718_0
  - python=3.12.10=h9ccd52b_0_cpython
  - readline=8.2=h7cca4af_2
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sqlite=3.49.1=h2e4c9dc_2
  - tk=8.6.13=h1abcd95_1
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=h357f2ed_0
  - xz-gpl-tools=5.8.1=h357f2ed_0
  - xz-tools=5.8.1=hd471939_0
  - pip:
      - astropy==7.0.1
      - astropy-iers-data==0.2025.5.5.0.38.14
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.57.0
      - kiwisolver==1.4.8
      - lxml==5.4.0
      - matplotlib==3.10.1
      - numpy==2.2.5
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - pyerfa==2.0.1.5
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - six==1.17.0
      - tqdm==4.67.1
      - tzdata==2025.2
prefix: /Users/vkostov/miniforge3/envs/pandora
